[2022-03-14 02:49:48,016] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2022-03-14T02:48:50.278738+00:00 [queued]>
[2022-03-14 02:49:48,019] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2022-03-14T02:48:50.278738+00:00 [queued]>
[2022-03-14 02:49:48,020] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 02:49:48,020] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-03-14 02:49:48,020] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 02:49:48,025] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-03-14T02:48:50.278738+00:00
[2022-03-14 02:49:48,027] {standard_task_runner.py:52} INFO - Started process 14043 to run task
[2022-03-14 02:49:48,031] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2022-03-14T02:48:50.278738+00:00', '--job-id', '22', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpafed6w_0', '--error-file', '/tmp/tmp92_bh645']
[2022-03-14 02:49:48,031] {standard_task_runner.py:77} INFO - Job 22: Subtask is_api_available
[2022-03-14 02:49:48,057] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2022-03-14T02:48:50.278738+00:00 [running]> on host airflowvm
[2022-03-14 02:49:48,088] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T02:48:50.278738+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-14T02:48:50.278738+00:00
[2022-03-14 02:49:48,088] {http.py:97} INFO - Poking: api/
[2022-03-14 02:49:48,091] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2022-03-14 02:49:48,091] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-03-14 02:49:48,290] {base.py:243} INFO - Success criteria met. Exiting.
[2022-03-14 02:49:48,292] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220314T024850, start_date=20220314T024948, end_date=20220314T024948
[2022-03-14 02:49:48,306] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-14 02:49:48,352] {local_task_job.py:151} INFO - Task exited with return code 0
